# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-03-07 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_list', jsonfield.fields.JSONField(default=[])),
            ],
        ),
    ]
